name: Test, build & release
on: push
jobs:
  njsscan:
    name: njsscan code scanning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
  codeql:
    needs: njsscan
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  release:
    needs: codeql
    name: Build & release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn add electron-builder
      - name: Build/release Electron app
        env:
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
  mirror:
    needs: release
    name: Mirror code to opencode.net
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://www.opencode.net/ransome/sleek.git"
      env:
        GITLAB_HOSTNAME: "opencode.net"
        GITLAB_USERNAME: "ransome"
        GITLAB_PASSWORD: ${{ secrets.gitlab_password }}
        GITLAB_PROJECT_ID: "https://www.opencode.net/ransome/sleek/edit"
        GITHUB_TOKEN: ${{ secrets.github_token }}

#  publish-aur-package:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Publish AUR package
#        uses: KSXGitHub/github-actions-deploy-aur@v2
#        with:
#          pkgname: sleek
#          pkgbuild: ./PKGBUILD
#          commit_username: ${{ secrets.AUR_USERNAME }}
#          commit_email: ${{ secrets.AUR_EMAIL }}
#          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
#          commit_message: Update to latest sleek release
